### ISSUE TITLE
Pidor of the day

### ISSUE THREAD

**Issue by jDan735** [jDan735/jdan734-bot#25]
Add a command defining a pidor of the day

## Commands
* `/pidor`
* `/pidorreg`
* `/pidorstat`

**Comment by Aphanasiy** [comment]
А это не противоречит правилам чата?

**Comment by jDan735** [comment]
Это делается для других чятов, чтобы заменить sublimebot

**Comment by jDan735** [comment]
Для профсоюза можно будет сделать "бан дня", то есть то же самое, что и пидор дня, но "счасливчика" будут банить на минуту
